version: '3.8'

services:
  database:
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=otel_app
    ports:
      - "5432:5432"
    command:
      - 'postgres'
      - '-c'
      - 'effective_cache_size=1024MB'
    volumes:
      - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql
